### ISSUE TITLE
meta data: store (project specific) meta data in wdbmeta.xml

### ISSUE THREAD

**Issue by dariok** [dariok/wdbplus#316]
- [ ] section in `wdbmeta.xml` for (project specific and general) meta data
- [ ] retrieval via endpoint (cf. #152)
- [ ] generation/update via trigger on storage of data in collection
